export const HW_CREATE_REQUEST = 'HW_CREATE_REQUEST';
export const HW_CREATE_SUCCESS = 'HW_CREATE_SUCCESS';
export const HW_CREATE_FAIL = 'HW_CREATE_FAIL';
export const HW_CREATE_RESET = 'HW_CREATE_RESET';

export const HW_UPDATE_REQUEST = 'HW_UPDATE_REQUEST';
export const HW_UPDATE_SUCCESS = 'HW_UPDATE_SUCCESS';
export const HW_UPDATE_FAIL = 'HW_UPDATE_FAIL';
export const HW_UPDATE_RESET = 'HW_UPDATE_RESET';

export const HW_LIST_FOR_TEACHER_REQUEST = 'HW_LIST_FOR_TEACHER_REQUEST';
export const HW_LIST_FOR_TEACHER_SUCCESS = 'HW_LIST_FOR_TEACHER_SUCCESS';
export const HW_LIST_FOR_TEACHER_FAIL = 'HW_LIST_FOR_TEACHER_FAIL';
export const HW_LIST_FOR_TEACHER_RESET = 'HW_LIST_FOR_TEACHER_RESET';

export const HW_DETAILS_REQUEST = 'HW_DETAILS_REQUEST';
export const HW_DETAILS_SUCCESS = 'HW_DETAILS_SUCCESS';
export const HW_DETAILS_FAIL = 'HW_DETAILS_FAIL';
export const HW_DETAILS_RESET = 'HW_DETAILS_RESET';

export const HW_DELETE_SUCCESS = 'HW_DELETE_SUCCESS';
export const HW_DELETE_REQUEST = 'HW_DELETE_REQUEST';
export const HW_DELETE_FAIL = 'HW_DELETE_FAIL';

export const ADD_QUESTION_TO_HW_REQUEST = 'ADD_QUESTION_TO_HW_REQUEST';
export const ADD_QUESTION_TO_HW_SUCCESS = 'ADD_QUESTION_TO_HW_SUCCESS';
export const ADD_QUESTION_TO_HW_FAIL = 'ADD_QUESTION_TO_HW_FAIL';
export const ADD_QUESTION_TO_HW_RESET = 'ADD_QUESTION_TO_HW_RESET';

export const DELETE_QUESTION_TO_HW_REQUEST = 'DELETE_QUESTION_TO_HW_REQUEST';
export const DELETE_QUESTION_TO_HW_SUCCESS = 'DELETE_QUESTION_TO_HW_SUCCESS';
export const DELETE_QUESTION_TO_HW_FAIL = 'DELETE_QUESTION_TO_HW_FAIL';
export const DELETE_QUESTION_TO_HW_RESET = 'DELETE_QUESTION_TO_HW_RESET';

export const HW_DETAILS_ADD_CLASS_REQUEST = 'HW_DETAILS_ADD_CLASS_REQUEST';
export const HW_DETAILS_ADD_CLASS_SUCCESS = 'HW_DETAILS_ADD_CLASS_SUCCESS';
export const HW_DETAILS_ADD_CLASS_FAIL = 'HW_DETAILS_ADD_CLASS_FAIL';
export const HW_DETAILS_ADD_CLASS_RESET = 'HW_DETAILS_ADD_CLASS_RESET';
