export const MY_HW_IN_CLASS_REQUEST = 'MY_HW_IN_CLASS_REQUEST';
export const MY_HW_IN_CLASS_SUCCESS = 'MY_HW_IN_CLASS_SUCCESS';
export const MY_HW_IN_CLASS_FAIL = 'MY_HW_IN_CLASS_FAIL';
export const MY_HW_IN_CLASS_RESET = 'MY_HW_IN_CLASS_RESET';
